### ISSUE TITLE
Object copy for listConcept()

### ISSUE THREAD

**Issue by wcandillon** [28msec/nolap-report-editor#1]
Currently listConcept creates a copy: https://github.com/28msec/nolap-report-editor/blob/report-editor/src/report.js#L245

I would like it to return

``` javascript
model.Hypercubes['xbrl:DefaultHypercube']
                .Aspects['xbrl:Concept']
                .Domains['xbrl:ConceptDomain']
                .Members
```

instead, it order to more easily sync the model and the view. Would it make sense to you?

**Comment by wcandillon** [comment]
@dknochen if you agree, I can add `listConceptsByRef()` in the meantime.

**Comment by dknochen** [comment]
sure.
