### ISSUE TITLE
Cannot transition to abstract state 'report.taxonomy'

### ISSUE THREAD

**Issue by ghislainfourny** [28msec/nolap-report-editor#134]
Error: Cannot transition to abstract state 'report.taxonomy'
    at Object.v.transitionTo (http://reports.secxbrl.info/scripts/340c1b5b.scripts.js:5:17831)
    at Object.v.go (http://reports.secxbrl.info/scripts/340c1b5b.scripts.js:5:17056)
    at http://reports.secxbrl.info/scripts/340c1b5b.scripts.js:1:1041
    at http://reports.secxbrl.info/scripts/340c1b5b.scripts.js:3:25740
    at g (http://reports.secxbrl.info/scripts/340c1b5b.scripts.js:2:15008)
    at http://reports.secxbrl.info/scripts/340c1b5b.scripts.js:2:16731 340c1b5b.scripts.js:3
(anonymous function) 340c1b5b.scripts.js:3
(anonymous function) 340c1b5b.scripts.js:2
(anonymous function) 340c1b5b.scripts.js:3
g 340c1b5b.scripts.js:2
(anonymous function)

**Comment by wcandillon** [comment]
@gislenius which URL is invoked? On which browser?

**Comment by ghislainfourny** [comment]
@wcandillon I was here http://reports.secxbrl.info/1f604739-ff99-498d-8c51-5b955339fe60/filters and tried to click on "Taxonomy" to go back to the first page.

**Comment by wcandillon** [comment]
Nice catch! thks a lot!
