### ISSUE TITLE
Authentication issue

### ISSUE THREAD

**Issue by wcandillon** [28msec/nolap-report-editor#23]
https://www.dropbox.com/s/atmn1u067dvi2v1/Screenshot%202014-07-07%2019.52.34.png

@dknochen in the first request, the saved token is not picked up. Maybe there is an issue with with the lifetime of the token client side. let's look at it tomorrow.

**Comment by dknochen** [comment]
I cannot reproduce this

**Comment by wcandillon** [comment]
@dknochen Do we agree that the number of log outs is too be in the report editor at the moment?
Sometimes it even feels random. Is it smooth sailing on your side regarding this?

**Comment by dknochen** [comment]
@wcandillon I think this is fixed in the cellfire-d branch. Can you test it?
