### ISSUE TITLE
Element doesn't match concept

### ISSUE THREAD

**Issue by wcandillon** [28msec/nolap-report-editor#27]
Iterating over a presentation tree elements finds concept names which doesn't exist. See https://github.com/28msec/nolap-report-editor/blob/cellfire/app/report/taxonomy/taxonomy.js#L57

**Comment by dknochen** [comment]
the report was broken

**Comment by wcandillon** [comment]
@dknochen What are the securities that prevent us for such "broken" report to be stored on the server?

**Comment by dknochen** [comment]
https://github.com/28msec/nolap-report-editor/issues/78
