### ISSUE TITLE
addConcept() name is inconsistent with createNew*() methods

### ISSUE THREAD

**Issue by wcandillon** [28msec/nolap-report-editor#33]

**Comment by wcandillon** [comment]
Also there seems to be an inconsistency with the following 3 methods:
findInConceptMap 

``` javascript
var referencesInConceptMapsArray = this.findInConceptMap(name);
var referencesInPresentationArray = this.findInTree('Presentation', name);
var referencesInRulesArray = this.findInRules(name);
```

there seems to be the same problem with `getConceptMap()` vs `getNetwork('Presentation').Trees`.

@dknochen A good way to unify this api would to be generate its jsdoc

**Comment by dknochen** [comment]
@wcandillon why is it inconsistent? add\* functions are not semantically equivalent with createNew\* functions: add\* adds something to the model, createNew\* instantiates a report element - e.g. a Map - without adding it to the model.

**Comment by wcandillon** [comment]
@dknochen What about my second comment?
