### ISSUE TITLE
only allow fac: prefixed concepts in a simple rule?

### ISSUE THREAD

**Issue by dknochen** [28msec/nolap-report-editor#48]
Hi, 

The initial version of fac:TemporaryEquity imputation is based on a "us-gaap:RedeemableNoncontrollingInterestEquityCommonCarryingAmount":

---

for $facts in facts:facts-for-internal((
                "fac:TemporaryEquity",
                "us-gaap:RedeemableNoncontrollingInterestEquityCommonCarryingAmount"), $hypercube, $aligned-filter, $concept-maps, $rules, $cache, $options)
## group by $canonical-filter-string := 

The rule editor doesn't allow me to convert this, as it automatically assumes that the Arithmetic Rule member has a "fac:" prefix 

<image.png>

For now, as a work around I used RedeemableNoncontrollingInterest instead, in the Arhitmetic Rule.

Thanks, 
Emma

**Comment by dknochen** [comment]
That’s a good point. I think we should discuss if a rule can only be based on concepts
defined in the report in order to be self-contained.

Matthias

**Comment by dknochen** [comment]
I agree it needs a quick discussion. I don't see a problem with supporting any prefix in the simple formulas. 

On the other hand, you could also add a mapping to the us-gaap concept, but that seems cumbersome.

**Comment by MatthiasBrantner** [comment]
> I agree it needs a quick discussion. I don't see a problem with supporting any prefix in the simple formulas.
> 
> On the other hand, you could also add a mapping to the us-gaap concept, but that seems cumbersome.
> 
> It might be a little overhead but we need to understand the semantics of a report and the rules that it
> contains. The question is whether rules and imputations should be allowed to go to the outside
> world or whether the taxonomy/report is closed with that respect. The advantage being that there
> is one clear channel that goes to the outside world.

I think we should start with this restriction and eventually open it up if required. If it’s too cumbersome,
the editor can always provide an easy way for creating such a concept.

Matthias

**Comment by dknochen** [comment]
this has been discussed and been agreed on
