### ISSUE TITLE
fac:NetCashFlowsFromFinancingActivities rule (new format) did not apply

### ISSUE THREAD

**Issue by emma28** [28msec/nolap-report-editor#50]
![image](https://cloud.githubusercontent.com/assets/6932941/3580984/59f16454-0be2-11e4-9868-abd3be4803b9.png)

http://beta.secxbrl.info/entity/0000051143/information/2013/FY

![image](https://cloud.githubusercontent.com/assets/6932941/3580993/90c583b6-0be2-11e4-9ad4-4771c0a9514c.png)

**Comment by dknochen** [comment]
@emma28: I double checked with the new rules editor and it's fixed in there (It was a problem in the code generation). So, I close this one as we will release the new one soon.
