### ISSUE TITLE
improve text in confirmation 

### ISSUE THREAD

**Issue by MatthiasBrantner** [28msec/nolap-report-editor#76]
![report_editor](https://cloud.githubusercontent.com/assets/6068900/3677507/316dd088-1292-11e4-8e7f-adc48a4e3c76.jpg)

**Comment by dknochen** [comment]
I wanted to distinguish between a single synonym and a complete mapping. In this case a complete mapping is deleted which might have several synonyms. Could you propose something to improve this message?

**Comment by MatthiasBrantner** [comment]
Does it matter to the user in this case? I think it's only confusing. There are 1 to n synonyms. That's all the user needs to know.

**Comment by dknochen** [comment]
changed it to "Several Synonyms"

**Comment by wcandillon** [comment]
this issue doesn't seem to be linked to a pull request.

**Comment by dknochen** [comment]
https://github.com/28msec/nolap-report-editor/commit/a2a3c6a97aa380da3658ba9c33029063b232222f#diff-4ce0f42898e071866990e5a10ed3fef4
