### ISSUE TITLE
Are fields in the report model up to date?

### ISSUE THREAD

**Issue by wcandillon** [28msec/nolap-report-editor#83]
@dknochen 
https://github.com/28msec/nolap-report-editor/blob/master/tests/unit/report.test.js#L12

It seems to be deprecated fields? description, role, prefix?

**Comment by dknochen** [comment]
@wcandillon why are these deprecated? They are not shown in the UI right now. This doesn't make them deprecated?

**Comment by wcandillon** [comment]
@dknochen  got it
