### ISSUE TITLE
newly created reports should have an abstract root element by default

### ISSUE THREAD

**Issue by dknochen** [28msec/nolap-report-editor#88]
the root element should be autogenerated. All reports should have an abstract root.

**Comment by dknochen** [comment]
@MatthiasBrantner what do you think about this? Does it make sense to you? The definition model and therefore, also the spreadsheet view requires an abstract root element.

**Comment by MatthiasBrantner** [comment]
Could you help me understand why they require an abstract root to be present?

**Comment by dknochen** [comment]
Currently, the definition model requires a single source element from the presentation. As discussed on skype, we should prevent deletion of this root element and also disallow multiple roots. Per default, the root should have the same label as the report (which can still be changed).

**Comment by wcandillon** [comment]
Agreed on the resolution of the bug.
