### ISSUE TITLE
restructure unit/e2e tests directory strucures

### ISSUE THREAD

**Issue by dknochen** [28msec/nolap-report-editor#89]
align it to the app dir structure (by structure or by naming convention)

**Comment by wcandillon** [comment]
@dknochen absolutely it does. We just need to know how it affects the build system (these are excluded at build time, I'm not sure what's the selection pattern for that right now but cannot be hard I guess).

**Comment by wcandillon** [comment]
As described from the angularjs team at https://docs.google.com/document/d/1XXMvReO8-Awi1EZXAXS4PzDzdNvV6pGcuaF4Q9821Es/pub
